apiVersion: v1
kind: Service
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  selector:
    app: auth
  type: NodePort
  ports:
  - protocol: TCP         
    port: 8080
    targetPort : 80
