apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-cont
    image: mysql:5.6
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /test-pd
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: mysql-pv-claim      
            
