apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
  

