apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  securityContext:
    fsGroup: 2000
  containers:
    - name: mobileapp
      image: linuxacademycontent/candy-service:1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
